# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='person.proto',
  package='person_proto',
  serialized_pb='\n\x0cperson.proto\x12\x0cperson_proto\"*\n\x06Person\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x12\n\nbirth_year\x18\x02 \x02(\x05')




_PERSON = descriptor.Descriptor(
  name='Person',
  full_name='person_proto.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='person_proto.Person.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='birth_year', full_name='person_proto.Person.birth_year', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=72,
)



class Person(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PERSON
  
  # @@protoc_insertion_point(class_scope:person_proto.Person)

# @@protoc_insertion_point(module_scope)
